export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_ALIEN_SUCCESS = 'REQUEST_ALIEN_SUCCESS';
export const REQUEST_ALIEN_PENDING = 'REQUEST_ALIEN_PENDING';
export const REQUEST_ALIEN_FAILED = 'REQUEST_ALIEN_FAILED';